### PR TITLE
Feature/fe/476/create post

### PR DESCRIPTION
**Pull request by mtkamiloglu**
I created the post creation page. I used material UI to gain page modern look. I also mentioned differences in issue [#476](https://github.com/bounswe/bounswe2023group7/issues/476)

### CODE REVIEW

**Review by elifkizilky — CHANGES_REQUESTED** [review]
In the package.json file the react version is lowered to 16.8, I think it is because of the react-quill library. Can you check it and fix it to react version 18.2?

**Comment by mtkamiloglu** [comment]
I fixed the react version issue by changing it to 18.2.0

**Comment by elifkizilky** [comment]
I could not create a post when I tried. It gives the error code 403. When I looked at it, the request body is not the same as the one in the swagger documentation. We can postpone the merge of this branch until the backend is ready if that is suitable. Also a tags selection section should be added

**Comment by mtkamiloglu** [comment]
When I implemented this page, backend was not ready. I will connect to backend this week. After connecting the backend I will update this pull request.

**Comment by mtkamiloglu** [comment]
I connected page to the backend, added image upload feature and tag adding feature. Added snackbar to return response to the user. Changed 'Post' name to 'Thread' for clarity. Removed quill with mui/joy. It can be rewieved again @elifkizilky

**Review by elifkizilky — APPROVED** [review]
I tested it and it works as can be seen below. Later on, we will decide on the tags to be used on our platform and the tag part can be revised then.

Thank you for your work and time!

image

**Pull request merged**
