### PR TITLE
Feature/fe/423/game page revision

### PR DESCRIPTION
**Pull request by yunusemrealtug**
* getGame request is linked.
* Number of tabs are lowered.
* Tabs are reorganized.
* Basic game information boxes are reorganized.

### CODE REVIEW

**Comment by elifkizilky** [comment]
I found a minor inconvenience: In the tabs, when I click on the System Requirements, it opens the data for Platforms. The platform data is not shown anywhere else. Can you look at it?

**Comment by yunusemrealtug** [comment]
Now I edited there. It should be seem better.

**Comment by yunusemrealtug** [comment]
Thanks for the comment @elifkizilky, @mtkamiloglu can you review too, i need quick response.

**Review by mtkamiloglu — APPROVED** [review]
well written! thanks @yunusemrealtug

**Pull request merged**
