### PR TITLE
Added default properties such as Image Link and Description

### PR DESCRIPTION
**Pull request by mtkamiloglu**
I added default property input boxes for description and image link. I revised the form component and set error both input boxes if one of the fields is tried to be submitted empty.

### CODE REVIEW

**Review by elifkizilky — CHANGES_REQUESTED** [review]
- It gave me an error like this as if i left the description part blank too when i only left the image link part blank:

image



- Also, the description part can be multiline like this: 

image

- after the submission, it may redirect to the entity page although the entity page is under revision now :D

**Comment by mtkamiloglu** [comment]
I added changes you requested and fixed the error issue. @elifkizilky

**Comment by elifkizilky** [comment]
image

There was a small mistake in the types, I changed it to "Environment".

**Review by elifkizilky — APPROVED** [review]
I tested it and fixed some really minor things as I commented. Thanks for your time and effort.

**Pull request merged**
