### PR TITLE
Feature/mb/658/redirecting

### PR DESCRIPTION
**Pull request by senaal**
When edit or create pages are used, and when the back button is pressed, the edited fields were reappearing. When the edit or create status is successful, the back button is now redirected to the home page. (edit profile page, create-edit game, change password page) #658

### CODE REVIEW

**Comment by frknlke** [comment]
I reviewed the branch. After editing user profile, edited fields are still reappeared when I pressed back button. It should be fixed before merge. Other than that it looks good.

**Review by frknlke — CHANGES_REQUESTED** [review]
Edited fields are still reappearing in edit user profile page.

**Review by frknlke — APPROVED** [review]

**Comment by frknlke** [comment]
> Edited fields are still reappearing in edit user profile page.

My fault, now all is well. Well done.

**Review by haticerk — APPROVED** [review]
I reviewed the PR, everything seems okay. Well done!

**Pull request merged**
